[functions]
directory = "netlify/functions"

[[redirects]]
from = "/webhooks/yookassa"
to = "/.netlify/functions/yookassa-webhook"
status = 200
force = true

[[redirects]]
from = "/payment-return"
to = "/.netlify/functions/payment-return"
status = 200
force = true

[[redirects]]
from = "/s/*"
to = "/.netlify/functions/subscription-proxy"
status = 200
force = true

[[redirects]]
from = "/sub/*"
to = "/.netlify/functions/subscription-proxy"
status = 200
force = true
